export const genres = [
  {
    id: 1,
    genre: "Pop",
    author: `Alec Favale`,
    image: `https://images.unsplash.com/photo-1547355253-ff0740f6e8c1?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=627&q=80`,
    authorLink: `https://unsplash.com/fr/@alecfavale?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText`,
    unsplashLink: `https://unsplash.com/photos/MZJOBxOXbt0?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText`,
    gradient: `bg-gradient-to-l from-pink-300 via-purple-300 to-indigo-400 transition-all ease-in-out duration-1000 delay-200`,
  },
  {
    id: 2,
    genre: "Electronica",
    author: `James Owen`,
    image: `https://images.unsplash.com/photo-1525362081669-2b476bb628c3?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NXx8ZWxlY3Ryb25pY2ElMjBtdXNpY3xlbnwwfDF8MHx8&auto=format&fit=crop&w=500&q=60`,
    authorLink: `https://unsplash.com/fr/@jhjowen?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText`,
    unsplashLink: `https://unsplash.com/photos/c-NBiJrhwdM?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText`,
    gradient: `bg-gradient-to-l from-blue-700 via-blue-800 to-gray-900 transition-all ease-in-out duration-1000 delay-200`,
  },
  {
    id: 3,
    genre: "Jazz",
    author: `dimitri.photography`,
    image: `https://images.unsplash.com/flagged/photo-1569231290150-9c6200705c5b?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8amF6eiUyMG11c2ljfGVufDB8MXwwfHw%3D&auto=format&fit=crop&w=500&q=60`,
    authorLink: `https://unsplash.com/@dimitriphotography?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText`,
    unsplashLink: `https://unsplash.com/photos/ryFLoYs9YS4?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText`,
    gradient: `bg-gradient-to-l from-pink-500 via-red-500 to-yellow-500 transition-all ease-in-out duration-1000 delay-200`,
  },
  {
    id: 4,
    genre: "Classical",
    author: `Miti`,
    image: `https://images.unsplash.com/photo-1525954322486-aa196091220f?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8OXx8Y2xhc3NpY2FsJTIwbXVzaWN8ZW58MHwxfDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60`,
    authorLink: `https://unsplash.com/pt-br/@mitifotos?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText`,
    unsplashLink: `https://unsplash.com/photos/_h5yGdue66o?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText`,
    gradient: `bg-gradient-to-l from-gray-700 via-gray-900 to-black transition-all ease-in-out duration-1000 delay-200`,
  },
  {
    id: 5,
    genre: "Country",
    author: `Alex Blăjan`,
    image: `https://images.unsplash.com/photo-1490300472339-79e4adc6be4a?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=730&q=80`,
    authorLink: `https://unsplash.com/@alexb?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText`,
    unsplashLink: `https://unsplash.com/photos/QQgynUCd45I?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText`,
    gradient: `bg-gradient-to-l from-gray-200 via-gray-400 to-gray-600 transition-all ease-in-out duration-1000 delay-200`,
  },
];
